# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 133906d2924ed269f88b092c1a5f532e8bae830264a467161026e75bbd72ebc872f153950bbfb5e93ec0fd8bd97b2e83ac9425ee32b26f1620324a2a4568d3a1

test:
  secret_key_base: 9046820d74035dba9c37d1be75dc0114f6f51c74207e11a63d297d26050b85de43020cd0b3740d301f0649d323eafd0916ebca0e82490cb7b1909530d8babd54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
